// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides an AI symptom checker flow that allows patients to input their symptoms and receive a preliminary assessment in their local language.
 *
 * - aiSymptomChecker - A function that handles the symptom checking process.
 * - AiSymptomCheckerInput - The input type for the aiSymptomChecker function.
 * - AiSymptomCheckerOutput - The return type for the aiSymptomChecker function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiSymptomCheckerInputSchema = z.object({
  symptoms: z.string().describe('The symptoms the patient is experiencing.'),
  language: z.string().describe('The language in which the symptoms are described and the assessment should be provided.'),
});
export type AiSymptomCheckerInput = z.infer<typeof AiSymptomCheckerInputSchema>;

const AiSymptomCheckerOutputSchema = z.object({
  assessment: z.string().describe('A preliminary assessment of the symptoms, presented as a list of points. This includes possible conditions, potential reasons, suggested remedies/cures, danger assessment, and doctor recommendations, translated into the specified language.'),
  likelihoodEstimate: z.string().describe('An estimate of the likelihood that the symptoms match known conditions.'),
  disclaimer: z.string().describe('A disclaimer encouraging the user to speak to a medical professional.'),
});
export type AiSymptomCheckerOutput = z.infer<typeof AiSymptomCheckerOutputSchema>;

export async function aiSymptomChecker(input: AiSymptomCheckerInput): Promise<AiSymptomCheckerOutput> {
  return aiSymptomCheckerFlow(input);
}

const aiSymptomCheckerPrompt = ai.definePrompt({
  name: 'aiSymptomCheckerPrompt',
  input: {schema: AiSymptomCheckerInputSchema},
  output: {schema: AiSymptomCheckerOutputSchema},
  prompt: `You are an AI symptom checker that provides a preliminary assessment of symptoms to patients in their local language.

  Symptoms: {{{symptoms}}}
  Language: {{{language}}}

  Provide a preliminary assessment of the symptoms in the specified language. The assessment should be presented as a list of points or bullet points and cover the following aspects:
  - Possible conditions.
  - Potential reasons for the symptoms.
  - Suggested remedies and cures for the cause.
  - An assessment of how dangerous the symptoms might be.
  - Recommendations for which type of doctor to consult.

  Include an estimate of the likelihood that the symptoms match known conditions.
  Also include a disclaimer encouraging the user to speak to a medical professional.
  Make sure your response is in the specified language.

  Output in JSON format.
  `,
});

const aiSymptomCheckerFlow = ai.defineFlow(
  {
    name: 'aiSymptomCheckerFlow',
    inputSchema: AiSymptomCheckerInputSchema,
    outputSchema: AiSymptomCheckerOutputSchema,
  },
  async input => {
    const {output} = await aiSymptomCheckerPrompt(input);
    return output!;
  }
);

