export const languages = [
  { value: 'en', label: 'English' },
  { value: 'es', label: 'Español (Spanish)' },
  { value: 'fr', label: 'Français (French)' },
  { value: 'de', label: 'Deutsch (German)' },
  { value: 'sw', label: 'Kiswahili (Swahili)' },
  { value: 'hi', label: 'हिन्दी (Hindi)' },
  { value: 'zh', label: '中文 (Chinese)' },
  { value: 'ar', label: 'العربية (Arabic)' },
  { value: 'pt', label: 'Português (Portuguese)' },
  { value: 'ja', label: '日本語 (Japanese)' },
  { value: 'it', label: 'Italiano (Italian)' },
  { value: 'yo', label: 'Yoruba' }, // Added for Dr. Femi Adebayo
  { value: 'ru', label: 'Русский (Russian)' }, // Added for Dr. Lena Petrova
];

export const specialties = [
  { value: 'general', label: 'General Practice' },
  { value: 'cardiology', label: 'Cardiology' },
  { value: 'dermatology', label: 'Dermatology' },
  { value: 'pediatrics', label: 'Pediatrics' },
  { value: 'neurology', label: 'Neurology' },
  { value: 'oncology', label: 'Oncology' },
  { value: 'psychiatry', label: 'Psychiatry' },
];

export interface Doctor {
  id: string;
  name: string;
  specialty: string;
  languages: string[];
  location: string;
  rating: number;
  reviews: number;
  availability: string;
  image: string;
}

export const mockDoctors: Doctor[] = [
  {
    id: '1',
    name: 'Dr. Alice Smith',
    specialty: 'Cardiology',
    languages: ['English', 'Spanish'],
    location: 'New York, USA',
    rating: 4.8,
    reviews: 120,
    availability: 'Mon, Wed, Fri',
    image: 'https://picsum.photos/seed/doctor1/200/200',
  },
  {
    id: '2',
    name: 'Dr. Bob Johnson',
    specialty: 'Dermatology',
    languages: ['English', 'French'],
    location: 'London, UK',
    rating: 4.5,
    reviews: 95,
    availability: 'Tue, Thu',
    image: 'https://picsum.photos/seed/doctor2/200/200',
  },
  {
    id: '3',
    name: 'Dr. Carol Williams',
    specialty: 'Pediatrics',
    languages: ['English', 'German'],
    location: 'Berlin, Germany',
    rating: 4.9,
    reviews: 200,
    availability: 'Mon - Fri',
    image: 'https://picsum.photos/seed/doctor3/200/200',
  },
  {
    id: '4',
    name: 'Dr. David Brown',
    specialty: 'Neurology',
    languages: ['English'],
    location: 'Toronto, Canada',
    rating: 4.7,
    reviews: 150,
    availability: 'Mon, Tue, Thu',
    image: 'https://picsum.photos/seed/doctor4/200/200',
  },
  {
    id: '5',
    name: 'Dr. Eve Davis',
    specialty: 'General Practice',
    languages: ['English', 'Swahili'],
    location: 'Nairobi, Kenya',
    rating: 4.6,
    reviews: 80,
    availability: 'Wed, Fri, Sat',
    image: 'https://picsum.photos/seed/doctor5/200/200',
  },
  {
    id: '6',
    name: 'Dr. Priya Sharma',
    specialty: 'General Practice',
    languages: ['Hindi', 'English'],
    location: 'Mumbai, India',
    rating: 4.7,
    reviews: 110,
    availability: 'Tue, Thu, Sat',
    image: 'https://picsum.photos/seed/doctor6/200/200',
  },
  {
    id: '7',
    name: 'Dr. Kenji Tanaka',
    specialty: 'Oncology',
    languages: ['Japanese', 'English'],
    location: 'Tokyo, Japan',
    rating: 4.9,
    reviews: 180,
    availability: 'Mon, Wed',
    image: 'https://picsum.photos/seed/doctor7/200/200',
  },
  {
    id: '8',
    name: 'Dr. Li Wei',
    specialty: 'Pediatrics',
    languages: ['Chinese', 'English'],
    location: 'Shanghai, China',
    rating: 4.6,
    reviews: 130,
    availability: 'Tue, Fri',
    image: 'https://picsum.photos/seed/doctor8/200/200',
  },
  {
    id: '9',
    name: 'Dr. Sofia Rossi',
    specialty: 'Cardiology',
    languages: ['Spanish', 'Portuguese', 'English'],
    location: 'Buenos Aires, Argentina',
    rating: 4.8,
    reviews: 140,
    availability: 'Mon, Wed, Fri',
    image: 'https://picsum.photos/seed/doctor9/200/200',
  },
  {
    id: '10',
    name: 'Dr. Mateo Silva',
    specialty: 'Neurology',
    languages: ['Portuguese', 'Spanish'],
    location: 'São Paulo, Brazil',
    rating: 4.5,
    reviews: 90,
    availability: 'Tue, Thu',
    image: 'https://picsum.photos/seed/doctor10/200/200',
  },
  {
    id: '11',
    name: 'Dr. Olivia Wilson',
    specialty: 'Dermatology',
    languages: ['English'],
    location: 'Sydney, Australia',
    rating: 4.7,
    reviews: 100,
    availability: 'Mon, Fri',
    image: 'https://picsum.photos/seed/doctor11/200/200',
  },
  {
    id: '12',
    name: 'Dr. Antoine Dubois',
    specialty: 'Psychiatry',
    languages: ['French', 'English'],
    location: 'Paris, France',
    rating: 4.6,
    reviews: 115,
    availability: 'Tue, Thu, Sat',
    image: 'https://picsum.photos/seed/doctor12/200/200',
  },
  {
    id: '13',
    name: 'Dr. Isabella Conti',
    specialty: 'General Practice',
    languages: ['Italian', 'English'],
    location: 'Rome, Italy',
    rating: 4.8,
    reviews: 125,
    availability: 'Mon, Wed',
    image: 'https://picsum.photos/seed/doctor13/200/200',
  },
  {
    id: '14',
    name: 'Dr. Femi Adebayo',
    specialty: 'Pediatrics',
    languages: ['English', 'Yoruba'],
    location: 'Lagos, Nigeria',
    rating: 4.4,
    reviews: 75,
    availability: 'Wed, Fri',
    image: 'https://picsum.photos/seed/doctor14/200/200',
  },
  {
    id: '15',
    name: 'Dr. Omar Hassan',
    specialty: 'Cardiology',
    languages: ['Arabic', 'English'],
    location: 'Dubai, UAE',
    rating: 4.9,
    reviews: 160,
    availability: 'Mon - Thu',
    image: 'https://picsum.photos/seed/doctor15/200/200',
  },
  {
    id: '16',
    name: 'Dr. Lena Petrova',
    specialty: 'Oncology',
    languages: ['Russian', 'English'],
    location: 'Moscow, Russia',
    rating: 4.7,
    reviews: 105,
    availability: 'Tue, Thu',
    image: 'https://picsum.photos/seed/doctor16/200/200',
  },
  {
    id: '17',
    name: 'Dr. Carlos Gomez',
    specialty: 'General Practice',
    languages: ['Spanish', 'English'],
    location: 'Mexico City, Mexico',
    rating: 4.6,
    reviews: 95,
    availability: 'Mon, Wed, Fri',
    image: 'https://picsum.photos/seed/doctor17/200/200',
  },
  {
    id: '18',
    name: 'Dr. Hanna Müller',
    specialty: 'Dermatology',
    languages: ['German', 'English'],
    location: 'Munich, Germany',
    rating: 4.8,
    reviews: 135,
    availability: 'Tue, Fri',
    image: 'https://picsum.photos/seed/doctor18/200/200',
  },
  {
    id: '19',
    name: 'Dr. Ahmed Al Farsi',
    specialty: 'Pediatrics',
    languages: ['Arabic', 'English'],
    location: 'Riyadh, Saudi Arabia',
    rating: 4.5,
    reviews: 85,
    availability: 'Sun, Tue, Thu',
    image: 'https://picsum.photos/seed/doctor19/200/200',
  },
  {
    id: '20',
    name: 'Dr. Chloe Dubois', // Note: Same last name as Dr. Antoine Dubois, but different person/specialty
    specialty: 'Psychiatry',
    languages: ['French', 'English'],
    location: 'Montreal, Canada',
    rating: 4.7,
    reviews: 110,
    availability: 'Mon, Wed',
    image: 'https://picsum.photos/seed/doctor20/200/200',
  },
];

export const userRoles = [
  { value: 'patient', label: 'Patient' },
  { value: 'doctor', label: 'Doctor' },
];
